twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        system_name: '%systemname%'
        system_country: '%systemcountry%'
        feature_selfregister: '%selfregister%'
        feature_doubleoptin: '%doubleoptin%'
        feature_invitation: '%invitation%'