twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        system_name: '%systemname%'
        system_country: '%systemcountry%'
        feature_selfregister: '%selfregister%'
        feature_doubleoptin: '%doubleoptin%'
        feature_invitation: '%invitation%'

when@test:
    twig:
        strict_variables: true
