framework:
    workflows:
        foto_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
            supports:
                - App\Entity\Item
            initial_marking: Avise
            places:
                - Avise
                - Vorbereitung
                - Foto
                - Retusche
                - QA
                - Published
            transitions:
                angeliefert:
                    guard: "is_granted('ROLE_CONTENT')"
                    from: Avise
                    to: Vorbereitung
                gestylt:
                    guard: "is_granted('ROLE_CONTENT')"
                    from: Vorbereitung
                    to: Foto
                fotografiert:
                    guard: "is_granted('ROLE_FOTO')"
                    from: Foto
                    to: Retusche
                retuschiert:
                    guard: "is_granted('ROLE_FOTO')"
                    from: Retusche
                    to: QA
                akzeptiert:
                    guard: "is_granted('ROLE_QA')"
                    from: QA
                    to: Published
                zurückgewiesen:
                    guard: "is_granted('ROLE_QA')"
                    from: QA
                    to: Foto
