framework:
    workflows:
        photo_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
            supports:
                - App\Entity\Item
            initial_marking: Avise
            places:
                - Avise
                - Styling
                - Photo
                - Retouching
                - QA
                - Published
            transitions:
                delivered:
                    guard: "is_granted('ROLE_CONTENT')"
                    from: Avise
                    to: Styling
                styled:
                    guard: "is_granted('ROLE_CONTENT')"
                    from: Styling
                    to: Photo
                photographed:
                    guard: "is_granted('ROLE_PHOTO')"
                    from: Photo
                    to: Retouching
                retouched:
                    guard: "is_granted('ROLE_PHOTO')"
                    from: Retouching
                    to: QA
                accepted:
                    guard: "is_granted('ROLE_QA')"
                    from: QA
                    to: Published
                rejected:
                    guard: "is_granted('ROLE_QA')"
                    from: QA
                    to: Photo
